---
# Install nodejs and npm module deps
- name: nodejs install block
  block:
    - name: Check for nodejs
      stat:
        path: "{{ node_path }}/node"
      register: node_check

    - name: Install nodejs
      unarchive:
        src: "https://nodejs.org/dist/v{{ node_version }}/node-v{{ node_version }}-linux-x64.tar.xz"
        dest: "{{ node_install_location }}"
        remote_src: yes
        owner: root
        group: root
        extra_opts: "--strip-components=1"
      when: node_check.stat.exists == false

    - name: Install NPM modules
      npm:
        name: "{{ item }}"
        global: yes
        state: present
      with_items:
        - knex-migrator
        # - ghost-cli

    - name: Adding node_path to PATH
      template:
        src: nodejs.sh.j2
        dest: /etc/profile.d/nodejs.sh
        owner: root
        group: root
        mode: 0644
